version: '1'

services:
  springboot-container:
    image: spring-boot-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-container
    ports:
      - "8080-8100:8080"